### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by shengxianye** [eleme/ruskit#51]
[root@sh-redis-01 env]# ruskit -h
Traceback (most recent call last):
  File "/www/env/python27/bin/ruskit", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/www/env/python27/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/www/env/python27/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/www/env/python27/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: redis>=2.10.5

[root@sh-redis-01 env]# pip list
bson (0.4.6)
distribute (0.6.14)
elasticsearch (2.4.0)
funcsigs (1.0.2)
hiredis (0.2.0)
mock (2.0.0)
MySQL-python (1.2.5)
mysql-replication (0.11)
pbr (1.10.0)
pip (7.1.2)
pymongo (3.4.0)
PyMySQL (0.7.10)
pytz (2016.10)
redis (2.10.5)
requests (2.11.1)
ruskit (0.0.23)
setuptools (0.6rc11)
six (1.10.0)
urllib3 (1.17)

**Comment by shengxianye** [comment]
环境提示不友善，不知道哪里出错了
